//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_userinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_userinfo()
        {
            this.tb_XXUser = new HashSet<tb_XXUser>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Limit { get; set; }
        public string Email { get; set; }
        public byte[] oImage { get; set; }
        public string KaoQin { get; set; }
        public Nullable<short> AtWork { get; set; }
        public Nullable<System.DateTime> outworktime { get; set; }
        public Nullable<System.DateTime> inworktime { get; set; }
        public byte[] signname { get; set; }
        public string Desktop { get; set; }
        public Nullable<System.DateTime> ActiveTime { get; set; }
        public string Role_OA { get; set; }
        public string Role_PX { get; set; }
        public Nullable<bool> Existed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_XXUser> tb_XXUser { get; set; }
    }
}
