//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_XXUser
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string 英文名 { get; set; }
        public string 部门 { get; set; }
        public Nullable<int> YwzID { get; set; }
        public Nullable<double> 性别 { get; set; }
        public string 职务 { get; set; }
        public Nullable<System.DateTime> 任职时间 { get; set; }
        public string 级别 { get; set; }
        public string 民族 { get; set; }
        public string 政治面貌 { get; set; }
        public string 籍贯 { get; set; }
        public string 身份证号 { get; set; }
        public string 学历 { get; set; }
        public string 专业 { get; set; }
        public string 毕业学校 { get; set; }
        public Nullable<System.DateTime> 毕业时间 { get; set; }
        public string 学位 { get; set; }
        public string 学历1 { get; set; }
        public string 专业1 { get; set; }
        public string 毕业学校1 { get; set; }
        public Nullable<System.DateTime> 毕业时间1 { get; set; }
        public string 学位1 { get; set; }
        public string 职称 { get; set; }
        public Nullable<System.DateTime> 职称取得时间 { get; set; }
        public string 户口所在地 { get; set; }
        public Nullable<System.DateTime> 入职时间 { get; set; }
        public string 以往在职 { get; set; }
        public string 户口性质 { get; set; }
        public string 家庭住址 { get; set; }
        public string 联系电话 { get; set; }
        public string 在秦居住地 { get; set; }
        public string 家庭成员 { get; set; }
        public string 婚育状况 { get; set; }
        public Nullable<System.DateTime> 结婚时间 { get; set; }
        public Nullable<System.DateTime> 生育时间 { get; set; }
        public string 家庭电话 { get; set; }
        public Nullable<System.DateTime> 参加工作时间 { get; set; }
        public string 以往工作经历 { get; set; }
        public Nullable<double> 工龄调整月份 { get; set; }
        public Nullable<double> 现工龄工资 { get; set; }
        public Nullable<System.DateTime> 核算月份 { get; set; }
        public string 劳动合同状态 { get; set; }
        public Nullable<System.DateTime> 劳动合同签订时间 { get; set; }
        public Nullable<System.DateTime> 劳动合同到期时间 { get; set; }
        public string 其它 { get; set; }
        public byte[] 照片 { get; set; }
        public Nullable<bool> 在职 { get; set; }
        public Nullable<decimal> 现工龄 { get; set; }
        public Nullable<decimal> 可计算工龄 { get; set; }
        public byte[] 签名 { get; set; }
        public Nullable<System.DateTime> 离职日期 { get; set; }
        public string 离职原因 { get; set; }
        public string 公司座机 { get; set; }
        public Nullable<bool> IsRealExist { get; set; }
        public Nullable<int> 核对完成 { get; set; }
    
        public virtual tb_userinfo tb_userinfo { get; set; }
    }
}
